ci:
    autofix_commit_msg: |
        ci: auto fixes from pre-commit hooks

        for more information, see https://pre-commit.ci
    autofix_prs: true
    autoupdate_commit_msg: 'ci: pre-commit autoupdate'
    autoupdate_schedule: monthly

fail_fast: true

repos:
  - repo: https://github.com/adamchainz/django-upgrade
    rev: '1.13.0'
    hooks:
      - id: django-upgrade
        args: [--target-version, "3.2"]
  -  repo: https://github.com/asottile/pyupgrade
     rev: v3.3.2
     hooks:
       -  id: pyupgrade
          args: ["--py310-plus"]
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.1.1
    hooks:
      - id: autoflake
        entry: bash -c 'autoflake "$@"; git add -u;' --
        language: python
        args:
          [
            "--in-place",
            "--remove-all-unused-imports",
            "--remove-unused-variables",
            "--expand-star-imports",
            "--ignore-init-module-imports",
          ]
        files: \.py$
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort
        entry: bash -c 'isort "$@"; git add -u;' --
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        entry: bash -c 'black "$@"; git add -u;' --
        language_version: python3.10
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
